FROM nvcr.io/nvidia/pytorch:19.12-py3

WORKDIR /app
RUN python3 -m pip install typing-extensions jupyter detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.10/index.html --upgrade




